// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIqOsplvZJOAmS3T41RBy9wm8zLxNdmXA',
    appId: '1:1064054835547:web:c46527809ce864042d727e',
    messagingSenderId: '1064054835547',
    projectId: 'ecommerce-app-86dd8',
    authDomain: 'ecommerce-app-86dd8.firebaseapp.com',
    storageBucket: 'ecommerce-app-86dd8.firebasestorage.app',
    measurementId: 'G-64WT5Q2VQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA23GYxYUeciR_DMrqeRUVaCVsyrsT5yQI',
    appId: '1:1064054835547:android:42d3dc16066c929a2d727e',
    messagingSenderId: '1064054835547',
    projectId: 'ecommerce-app-86dd8',
    storageBucket: 'ecommerce-app-86dd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQTxBDChd2BuEj6kYxj6MiJ0tAq-CaXF4',
    appId: '1:1064054835547:ios:3a2e5c5d3a6234e42d727e',
    messagingSenderId: '1064054835547',
    projectId: 'ecommerce-app-86dd8',
    storageBucket: 'ecommerce-app-86dd8.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

}